apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-agent-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
spec:
  ingressClassName: nginx
  rules:
  - host: agent.demo.72602.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: basic-agent-app
            port:
              number: 80